(ns leiningen.v.file
  (:require [clojure.string :as string]))

(defn- cache-source
  "Return Clojure source code for the version cache file"
  [version describe]
  (string/join "\n" [";; This code was automatically generated by the 'lein-v' plugin"
                     "(ns version)"
                     (format "(def version \"%s\")" version)
                     (format "(def raw-version \"%s\")" describe)
                     ""]))

(defn- cache-edn-source
  "return EDN data structure for the version cache EDN file"
  [version describe]
  (string/join "\n"[ "{"
                    (format ":version \"%s\"" version)
                    (format ":raw-version \"%s\"" describe)
                    "}"]))

(defn version
  "Peek into the source of the project to read the cached version"
  [file]
  (try
    (load-file file)
    (eval 'version/version)
    (catch Exception _)))

(defn cache
  "Write the version of the given Leiningen project to a file-backed cache"
  [path version describe]
  (spit path (cache-source version describe)))

(defn cache-edn
  [path version describe]
  (spit path (cache-edn-source version describe)))
