(ns leiningen.v.file
  (:use [clojure.string :only [join]]))

(defn- cache-source
  "Return Clojure source code for the version cache file"
  [version describe]
  (join "\n" [";; This code was automatically generated by the 'lein-v' plugin"
              "(ns version)"
              (format "(def version \"%s\")" version)
              (format "(def raw-version \"%s\")" describe)
              ""]))

(defn- cache-path
  "Return path to version cache file"
  [{:keys [source-paths]}]
  (str (first source-paths) "/version.clj"))

(defn version
  "Peek into the source of the project to read the cached version"
  [project]
  (try
    (load-file (cache-path project))
    (eval 'version/version)
    (catch Exception e nil)))

(defn cache
  "Write the version of the given Leiningen project to a file-backed cache"
  [{{describe :describe} :workspace version :version :as project}]
  (let [path (cache-path project)]
    (spit path (cache-source version describe))))
